### ISSUE TITLE
LandsAddon.getLandChunk now takes Location instead of Chunk

### ISSUE THREAD

**Issue by PhaserArray** [RHazDev/BlockRegenerator#4]
The issue occurs here:

https://github.com/hazae41/mc-blockregen/blob/1a58914eec8c1e380ad589a40a35f4e55f11cdfc/src/main/kotlin/Main.kt#L23

In newer versions of the lands plugin, that appears to take Location rather than Chunk as a parameter:

https://github.com/Angeschossen/Lands/blob/019c0cf7811131d51653248f4daa02a1b39f6a79/LandsAPI/src/me/angeschossen/lands/api/landsaddons/LandsAddons.java#L50

**Comment by PhaserArray** [comment]
Here is the error log for when it runs:



```
[06:44:00] [DefaultDispatcher-worker-1/INFO]: [Lands] [Addons] Added LandsAddon. Name: BlockRegen-Lands
[06:44:00] [DefaultDispatcher-worker-1/WARN]: [io.sentry.dsn.Dsn] *** Couldn't find a suitable DSN, Sentry operations will do nothing! See documentation: https://docs.sentry.io/clients/java/ ***
[06:44:00] [DefaultDispatcher-worker-1/WARN]: [io.sentry.DefaultSentryClientFactory] No 'stacktrace.app.packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry. See documentation: https://docs.sentry.io/clients/java/config/#in-application-stack-frames
[06:44:00] [DefaultDispatcher-worker-1/WARN]: Exception in thread "DefaultDispatcher-worker-1" java.lang.NoSuchMethodError: me.angeschossen.lands.api.landsaddons.LandsAddon.getLandChunk(Lorg/bukkit/Chunk;)Lme/angeschossen/lands/api/objects/LandChunk;
[06:44:00] [DefaultDispatcher-worker-1/WARN]: 	at hazae41.minecraft.blockregen.lands.MainKt$addController$1$1.invoke(Main.kt:23)
[06:44:00] [DefaultDispatcher-worker-1/WARN]: 	at hazae41.minecraft.blockregen.lands.MainKt$addController$1$1.invoke(Main.kt)
[06:44:00] [DefaultDispatcher-worker-1/WARN]: 	at hazae41.minecraft.blockregen.MainKt.shouldRestore(Main.kt:62)
[06:44:00] [DefaultDispatcher-worker-1/WARN]: 	at hazae41.minecraft.blockregen.MainKt$regen$1$1$9.invoke(Main.kt:130)
[06:44:00] [DefaultDispatcher-worker-1/WARN]: 	at hazae41.minecraft.blockregen.MainKt$regen$1$1$9.invoke(Main.kt)
[06:44:00] [DefaultDispatcher-worker-1/WARN]: 	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:133)
[06:44:00] [DefaultDispatcher-worker-1/WARN]: 	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156)
[06:44:00] [DefaultDispatcher-worker-1/WARN]: 	at hazae41.minecraft.blockregen.MainKt$regen$1.invokeSuspend(Main.kt:240)
[06:44:00] [DefaultDispatcher-worker-1/WARN]: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[06:44:00] [DefaultDispatcher-worker-1/WARN]: 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:234)
[06:44:00] [DefaultDispatcher-worker-1/WARN]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
[06:44:00] [DefaultDispatcher-worker-1/WARN]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
[06:44:00] [DefaultDispatcher-worker-1/WARN]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
[07:10:46] [pool-9-thread-1/INFO]: GroupManager - INFO -  Data files refreshed.
[07:17:00] [DefaultDispatcher-worker-3/INFO]: [Lands] [Addons] Couldn't add addon. Already initialized. Name: BlockRegen-Lands
[07:17:00] [DefaultDispatcher-worker-3/WARN]: Exception in thread "DefaultDispatcher-worker-3" java.lang.NoSuchMethodError: me.angeschossen.lands.api.landsaddons.LandsAddon.getLandChunk(Lorg/bukkit/Chunk;)Lme/angeschossen/lands/api/objects/LandChunk;
[07:17:00] [DefaultDispatcher-worker-3/WARN]: 	at hazae41.minecraft.blockregen.lands.MainKt$addController$1$1.invoke(Main.kt:23)
[07:17:00] [DefaultDispatcher-worker-3/WARN]: 	at hazae41.minecraft.blockregen.lands.MainKt$addController$1$1.invoke(Main.kt)
[07:17:00] [DefaultDispatcher-worker-3/WARN]: 	at hazae41.minecraft.blockregen.MainKt.shouldRestore(Main.kt:62)
[07:17:00] [DefaultDispatcher-worker-3/WARN]: 	at hazae41.minecraft.blockregen.MainKt$regen$1$1$9.invoke(Main.kt:130)
[07:17:00] [DefaultDispatcher-worker-3/WARN]: 	at hazae41.minecraft.blockregen.MainKt$regen$1$1$9.invoke(Main.kt)
[07:17:00] [DefaultDispatcher-worker-3/WARN]: 	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:133)
[07:17:00] [DefaultDispatcher-worker-3/WARN]: 	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156)
[07:17:00] [DefaultDispatcher-worker-3/WARN]: 	at hazae41.minecraft.blockregen.MainKt$regen$1.invokeSuspend(Main.kt:240)
[07:17:00] [DefaultDispatcher-worker-3/WARN]: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[07:17:00] [DefaultDispatcher-worker-3/WARN]: 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:234)
[07:17:00] [DefaultDispatcher-worker-3/WARN]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
[07:17:00] [DefaultDispatcher-worker-3/WARN]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
[07:17:00] [DefaultDispatcher-worker-3/WARN]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

**Comment by PhaserArray** [comment]
Sent PR #5 with the likely fix.

**Comment by PhaserArray** [comment]
Opened PR #5 with the likely fix.

**Comment by hazae41** [comment]
Merged
