### ISSUE TITLE
Residence expansion not work

### ISSUE THREAD

**Issue by kassadGLA** [RHazDev/BlockRegenerator#6]
Hello!
After last two updates of block-regen, `block-regen-residence` expansion stop working.
```
[00:09:19 ERROR]: Error occurred while enabling BlockRegen-Residence v2.1.2 (Is it up to date?)
java.lang.NoSuchMethodError: hazae41.minecraft.blockregen.MainKt.getControllers()Ljava/util/List;
        at hazae41.minecraft.blockregen.residence.MainKt.addController(Main.kt:18) ~[?:?]
        at hazae41.minecraft.blockregen.residence.Plugin.onEnable(Main.kt:33) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-186]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-186]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-186]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-186]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-186]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-186]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-186]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:870) ~[patched_1.14.4.jar:git-Paper-186]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
```
Best regards.

**Comment by pattplayz** [comment]
Also happens with the GriefPrevention plugin. Using BlockRegen 3.3.1 and GriefPrevention v16.12.0-d4d7ac4. Thanks!

```[23:53:48] [Server thread/INFO]: [BlockRegen-GriefPrevention] Enabling BlockRegen-GriefPrevention v2.1.2
[23:53:48] [Server thread/ERROR]: Error occurred while enabling BlockRegen-GriefPrevention v2.1.2 (Is it up to date?)
java.lang.NoSuchMethodError: hazae41.minecraft.blockregen.MainKt.getControllers()Ljava/util/List;
	at hazae41.minecraft.blockregen.griefprevention.MainKt.addController(Main.kt:17) ~[mc-blockregen-griefprevention-c3a6a2a2a4-1-bundle.jar:?]
	at hazae41.minecraft.blockregen.griefprevention.Plugin.onEnable(Main.kt:31) ~[mc-blockregen-griefprevention-c3a6a2a2a4-1-bundle.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.4.jar:git-Spigot-065a373-763e560]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.4.jar:git-Spigot-065a373-763e560]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.14.4.jar:git-Spigot-065a373-763e560]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [spigot-1.14.4.jar:git-Spigot-065a373-763e560]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [spigot-1.14.4.jar:git-Spigot-065a373-763e560]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [spigot-1.14.4.jar:git-Spigot-065a373-763e560]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:266) [spigot-1.14.4.jar:git-Spigot-065a373-763e560]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775) [spigot-1.14.4.jar:git-Spigot-065a373-763e560]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]```

**Comment by hazae41** [comment]
Fixed, please redownload your extension plugins
